// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: geBadaQ9fZ99mVFF7H8pNR
// Component: JGa7vdVggm
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import HomeCta from "../../HomeCta"; // plasmic-import: C0GpmRzG6iO6c/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_simple_light_landing_page.module.css"; // plasmic-import: geBadaQ9fZ99mVFF7H8pNR/projectcss
import * as sty from "./PlasmicCta2.module.css"; // plasmic-import: JGa7vdVggm/css

export type PlasmicCta2__VariantMembers = {
  otherFeature: "otherFeature";
};

export type PlasmicCta2__VariantsArgs = {
  otherFeature?: SingleBooleanChoiceArg<"otherFeature">;
};

type VariantPropType = keyof PlasmicCta2__VariantsArgs;
export const PlasmicCta2__VariantProps = new Array<VariantPropType>(
  "otherFeature"
);

export type PlasmicCta2__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicCta2__ArgsType;
export const PlasmicCta2__ArgProps = new Array<ArgPropType>("children");

export type PlasmicCta2__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultCta2Props {
  children?: React.ReactNode;
  otherFeature?: SingleBooleanChoiceArg<"otherFeature">;
  className?: string;
}

function PlasmicCta2__RenderFunc(props: {
  variants: PlasmicCta2__VariantsArgs;
  args: PlasmicCta2__ArgsType;
  overrides: PlasmicCta2__OverridesType;
  dataFetches?: PlasmicCta2__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <HomeCta
            className={classNames("__wab_instance", sty.homeCta__tP3XH)}
          />
        ),

        value: args.children
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCta2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCta2__VariantsArgs;
    args?: PlasmicCta2__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCta2__Fetches;
  } & Omit<PlasmicCta2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCta2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCta2__ArgProps,
      internalVariantPropNames: PlasmicCta2__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCta2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCta2";
  } else {
    func.displayName = `PlasmicCta2.${nodeName}`;
  }
  return func;
}

export const PlasmicCta2 = Object.assign(
  // Top-level PlasmicCta2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCta2
    internalVariantProps: PlasmicCta2__VariantProps,
    internalArgProps: PlasmicCta2__ArgProps
  }
);

export default PlasmicCta2;
/* prettier-ignore-end */
