// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: geBadaQ9fZ99mVFF7H8pNR
// Component: w68ESKotXW
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: SIZOkQZTgxKvx/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_simple_light_landing_page.module.css"; // plasmic-import: geBadaQ9fZ99mVFF7H8pNR/projectcss
import * as sty from "./PlasmicDApp.module.css"; // plasmic-import: w68ESKotXW/css

export type PlasmicDApp__VariantMembers = {
  unnamedGroupOfVariants: "unnamedVariant";
};

export type PlasmicDApp__VariantsArgs = {
  unnamedGroupOfVariants?: MultiChoiceArg<"unnamedVariant">;
};

type VariantPropType = keyof PlasmicDApp__VariantsArgs;
export const PlasmicDApp__VariantProps = new Array<VariantPropType>(
  "unnamedGroupOfVariants"
);

export type PlasmicDApp__ArgsType = {};
type ArgPropType = keyof PlasmicDApp__ArgsType;
export const PlasmicDApp__ArgProps = new Array<ArgPropType>();

export type PlasmicDApp__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
};

export interface DefaultDAppProps {
  dataFetches: PlasmicDApp__Fetches;
}

function PlasmicDApp__RenderFunc(props: {
  variants: PlasmicDApp__VariantsArgs;
  args: PlasmicDApp__ArgsType;
  overrides: PlasmicDApp__OverridesType;
  dataFetches?: PlasmicDApp__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style global jsx>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root,
            {
              [sty.root__unnamedGroupOfVariants_unnamedVariant]: hasVariant(
                variants,
                "unnamedGroupOfVariants",
                "unnamedVariant"
              )
            }
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header, {
              [sty.header__unnamedGroupOfVariants_unnamedVariant]: hasVariant(
                variants,
                "unnamedGroupOfVariants",
                "unnamedVariant"
              )
            })}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header"],
  header: ["header"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDApp__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDApp__VariantsArgs;
    args?: PlasmicDApp__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicDApp__Fetches;
  } & Omit<PlasmicDApp__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicDApp__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicDApp__ArgProps,
      internalVariantPropNames: PlasmicDApp__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicDApp__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDApp";
  } else {
    func.displayName = `PlasmicDApp.${nodeName}`;
  }
  return func;
}

export const PlasmicDApp = Object.assign(
  // Top-level PlasmicDApp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),

    // Metadata about props expected for PlasmicDApp
    internalVariantProps: PlasmicDApp__VariantProps,
    internalArgProps: PlasmicDApp__ArgProps
  }
);

export default PlasmicDApp;
/* prettier-ignore-end */
